version: '3.9'

services:
  vdc:
    build: .
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_GOOGLE_API_KEY: ${NEXT_PUBLIC_GOOGLE_API_KEY}
    volumes:
      - ./public/snapshots:/app/public/snapshots